# Generated by Django 2.2.7 on 2019-12-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stateadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('hobbies', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=50)),
                ('upload', models.FileField(upload_to='images')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bureauinfoapp.Age')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bureauinfoapp.Stateadd')),
            ],
        ),
    ]
