# Generated by Django 2.2.7 on 2019-12-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureauinfoapp', '0003_auto_20191217_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_profile',
            name='upload',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
